---
openapi: "3.0.0"
info:
  title: "Lasius API"
  description: "Track your time"
components:
  securitySchemes:
    cookieAuth: # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: XSRF-TOKEN  # cookie name
  schemas:
    models.Invitation:
      oneOf:
        - $ref: '#/components/schemas/models.JoinOrganisationInvitation'
        - $ref: '#/components/schemas/models.JoinProjectInvitation'
      discriminator:
        propertyName: type
        mapping:
          JoinOrganisationInvitation: '#/components/schemas/models.JoinOrganisationInvitation'
          JoinProjectInvitation: '#/components/schemas/models.JoinProjectInvitation'
    models.Tag:
      oneOf:
        - $ref: '#/components/schemas/models.SimpleTag'
        - $ref: '#/components/schemas/models.TagGroup'
        - $ref: '#/components/schemas/models.GitlabIssueTag'
        - $ref: '#/components/schemas/models.JiraIssueTag'
      discriminator:
        propertyName: type
        mapping:
          SimpleTag: '#/components/schemas/models.SimpleTag'
          TagGroup: '#/components/schemas/models.TagGroup'
          GitlabIssueTag: '#/components/schemas/models.GitlabIssueTag'
          JiraIssueTag: '#/components/schemas/models.JiraIssueTag'